[package]
name = "vortex"
version = "0.1.0"
edition = "2024.beta" 
license = "MIT"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]   

[dependencies]

[addresses]
vortex = "0x0"
treasury = "0x7"
