[package]
name = "vortex"
edition = "2024.beta" 
license = "MIT"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]   

[dependencies]
interest_bps = { r.mvr = "@interest/bps" }

[addresses]
vortex = "0x0"
treasury = "0x7"

[r.mvr]
network = "mainnet"