[package]
name = "vortex"
edition = "2024.beta" 
license = "Apache-2.0"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]   

[dependencies]
interest_access_control = { r.mvr = "@interest/acl" }
interest_bps = { r.mvr = "@interest/bps" }

[addresses]
vortex = "0x0"

[r.mvr]
network = "mainnet"
